chore: Update pytest
Tests fail immediately with:

```
TypeError: required field "lineno" missing from alias
```

See https://github.com/pytest-dev/pytest/pull/8540

Upgrading has the required fix.